### cadastro admin
POST http://localhost:4000/auth/admin/signup
Content-Type: application/json

{
    "name":"inutel",
    "email":"inuteiscoisas6@gmail.com",
    "password":"12345678910"
}

### login admin 
POST http://localhost:4000/auth/admin/login
Content-Type: application/json

{
    "email":"inuteiscoisas6@gmail.com",
    "password":"12345678910"
}
### inserir pessoa
POST http://localhost:4000/api/post/inserirProducao
Content-Type: application/json

{
    "nome":"cassiano",
    "idade":20,
    "nacionalidade":"brasileira",
    "atividade":"ator",
    "foto":"https://imgv3.fotor.com/images/homepage-feature-card/Carro-PNG.jpg",
}
### inserir post 
POST http://localhost:4000/api/post/adicionar
Content-Type: application/json

{
    "titulo":"planeta dos macacos",
    "sinopse":"planeta dos macacos a origem",
    "genero":"aventura",
    "avaliacao":5,
    "id_image":"https://imgv3.fotor.com/images/homepage-feature-card/Carro-PNG.jpg",
    "direcao_id":1,
    "id_funcionario":3,
    "id_traler":"https://media.istockphoto.com/id/2197216639/pt/v%C3%ADdeo/sugar-cane-planter-sugar-cane-harvester-agricultural-fields-agricultural-machine-drone-top.mp4?s=mp4-640x640-is&k=20&c=JHkmyTIwHy1ip-PYuHkvcOg4PtBgrekZtJsp2rg-YMw="
}