### cadastro admin
POST http://localhost:4000/auth/admin/signup
Content-Type: application/json

{
    "name":"cassique",
    "email":"sobralcassique@gmail.com",
    "password":"12345678910"
}

### login admin 
POST http://localhost:4000/auth/admin/login
Content-Type: application/json

{
    "email":"sobralcassique@gmail.com",
    "password":"12345678910"
}
### inserir pessoa
POST http://localhost:4000/api/post/inserirProducao
Content-Type: application/json

{
    "nome":"cassiano",
    "idade":20,
    "nacionalidade":"brasileira",
    "atividade":"ator",
    "foto":"https://imgv3.fotor.com/images/homepage-feature-card/Carro-PNG.jpg",
    "video":""
}