### cadastro admin
POST http://localhost:4000/auth/admin/signup
Content-Type: application/json

{
    "name":"inutel",
    "email":"inuteiscoisas6@gmail.com",
    "password":"12345678910"
}

### login admin 
POST http://localhost:4000/auth/admin/login
Content-Type: application/json

{
    "email":"inuteiscoisas6@gmail.com",
    "password":"12345678910"
}
### inserir pessoa
POST http://localhost:4000/api/post/inserirProducao
Content-Type: application/json

{
    "nome":"cassiano",
    "idade":20,
    "nacionalidade":"brasileira",
    "atividade":"ator",
    "foto":"https://imgv3.fotor.com/images/homepage-feature-card/Carro-PNG.jpg",
}
### inserir post 
POST http://localhost:4000/api/post/adicionar
Content-Type: application/json

{
    "titulo":"planeta dos macacos",
    "sinopse":"planeta dos macacos a origem",
    "genero":"aventura",
    "avaliacao":5,
    "id_image":"https://imgv3.fotor.com/images/homepage-feature-card/Carro-PNG.jpg",
    "direcao_id":1,
    "id_funcionario":1,
    "id_traler":"backend/videos/3629511-hd_720_900_24fps(1).mp4"
}